/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BooksRouteImport } from './routes/books'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiUnfurlRouteImport } from './routes/api.unfurl'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as WriteIndexRouteImport } from './routes/write.index'
import { Route as WriteIdRouteImport } from './routes/write.$id'
import { Route as ApiImagesKeyRouteImport } from './routes/api.images.$key'
import { Route as WriteIdPreviewRouteImport } from './routes/write.$id_.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnfurlRoute = ApiUnfurlRouteImport.update({
  id: '/api/unfurl',
  path: '/api/unfurl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteIndexRoute = WriteIndexRouteImport.update({
  id: '/write/',
  path: '/write/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteIdRoute = WriteIdRouteImport.update({
  id: '/write/$id',
  path: '/write/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesKeyRoute = ApiImagesKeyRouteImport.update({
  id: '/api/images/$key',
  path: '/api/images/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteIdPreviewRoute = WriteIdPreviewRouteImport.update({
  id: '/write/$id_/preview',
  path: '/write/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/unfurl': typeof ApiUnfurlRoute
  '/api/upload': typeof ApiUploadRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/write/$id': typeof WriteIdRoute
  '/write/': typeof WriteIndexRoute
  '/api/images/$key': typeof ApiImagesKeyRoute
  '/write/$id/preview': typeof WriteIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/unfurl': typeof ApiUnfurlRoute
  '/api/upload': typeof ApiUploadRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/write/$id': typeof WriteIdRoute
  '/write': typeof WriteIndexRoute
  '/api/images/$key': typeof ApiImagesKeyRoute
  '/write/$id/preview': typeof WriteIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/unfurl': typeof ApiUnfurlRoute
  '/api/upload': typeof ApiUploadRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/write/$id': typeof WriteIdRoute
  '/write/': typeof WriteIndexRoute
  '/api/images/$key': typeof ApiImagesKeyRoute
  '/write/$id_/preview': typeof WriteIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/unfurl'
    | '/api/upload'
    | '/posts/$slug'
    | '/write/$id'
    | '/write/'
    | '/api/images/$key'
    | '/write/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/books'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/unfurl'
    | '/api/upload'
    | '/posts/$slug'
    | '/write/$id'
    | '/write'
    | '/api/images/$key'
    | '/write/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/unfurl'
    | '/api/upload'
    | '/posts/$slug'
    | '/write/$id'
    | '/write/'
    | '/api/images/$key'
    | '/write/$id_/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiUnfurlRoute: typeof ApiUnfurlRoute
  ApiUploadRoute: typeof ApiUploadRoute
  PostsSlugRoute: typeof PostsSlugRoute
  WriteIdRoute: typeof WriteIdRoute
  WriteIndexRoute: typeof WriteIndexRoute
  ApiImagesKeyRoute: typeof ApiImagesKeyRoute
  WriteIdPreviewRoute: typeof WriteIdPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unfurl': {
      id: '/api/unfurl'
      path: '/api/unfurl'
      fullPath: '/api/unfurl'
      preLoaderRoute: typeof ApiUnfurlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/': {
      id: '/write/'
      path: '/write'
      fullPath: '/write/'
      preLoaderRoute: typeof WriteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/$id': {
      id: '/write/$id'
      path: '/write/$id'
      fullPath: '/write/$id'
      preLoaderRoute: typeof WriteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$key': {
      id: '/api/images/$key'
      path: '/api/images/$key'
      fullPath: '/api/images/$key'
      preLoaderRoute: typeof ApiImagesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/$id_/preview': {
      id: '/write/$id_/preview'
      path: '/write/$id/preview'
      fullPath: '/write/$id/preview'
      preLoaderRoute: typeof WriteIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiUnfurlRoute: ApiUnfurlRoute,
  ApiUploadRoute: ApiUploadRoute,
  PostsSlugRoute: PostsSlugRoute,
  WriteIdRoute: WriteIdRoute,
  WriteIndexRoute: WriteIndexRoute,
  ApiImagesKeyRoute: ApiImagesKeyRoute,
  WriteIdPreviewRoute: WriteIdPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
